themoment-team/imi-frontend

src/asset/imiLogo.tsx

> 이미 로고 제작
> 사용할때 `width`랑 `height`값으로 넘겨서 사용하세요
```tsx
//예시
<ImiLogo width="66" height="48" />
```

feature: 아이콘 로고 제작

---

src/app/layout.tsx

develop 브랜치 최신화
- develop 브랜치를 최신화합니다.

fix: text 제거

---

src/components/Footer/footer.css.ts
src/components/Footer/index.tsx
src/components/Header/index.tsx

> 페이지별 렌더링 예외처리
로그인, 회원가입페이지시 header제외,
로그인, 회원가입, 자기소개서 작성 페이지시 footer 제외

fix: 페이지별 렌더링 예외처리

---

src/components/Footer/footer.css.ts
src/components/Footer/index.tsx

> footer 배경색 변경
경로가 '/'일때 footer 배경색 하얀색으로 변경

fix: 경로가 "/"일때 footer색 하얀색으로 변경

---

src/pageContainer/ProfilePages/ProfileListPage/profileList.css.ts

> profile list 디자인 맞게 gap 추가 
> gap 추가

[fix] profile list 디자인 맞게 gap 추가 

---

src/components/Header/header.css.ts
src/pageContainer/WritePage/index.tsx
src/pageContainer/WritePage/write.css.ts

자기소개서 작성 페이지 반응형 작업 완료했습니다
- 자기소개서 작성 페이지 반응형 작업
- 헤더 반응형 수정

[feat] 자기소개서 작성 페이지 반응형 작업

---

src/components/Loading/index.tsx
src/components/Loading/loading.css.ts

> 로딩 컴포넌트 구현 완료했습니다. 
https://github.com/user-attachments/assets/7f1948d2-bdd3-48c6-9375-a0cbaf03a48d

[feat] 로딩 컴포넌트 퍼블리싱

---

src/components/MainPage/Section1/index.tsx
src/components/MainPage/Section1/section1.css.ts
src/components/MainPage/Section2/index.tsx
src/pageContainer/MainPage/index.tsx

section1화살표 클릭시 section2로 스크롤 내리기
section1화살표 클릭시 section2로 스크롤 내리기
https://github.com/user-attachments/assets/ed7f11e0-3e83-44d5-b087-9491a71d4a17

[feat]: 자동 스크롤 내리기 구현

---

src/libs/api/axiosInstance.ts
src/libs/api/index.ts
src/libs/index.ts

axios 인스턴스 설정 했습니다.
- axios 인스턴스 설정
- 서버 배포 후 URL 작성 필요

[feat] axios 인스턴스 설정

---

next.config.ts
src/libs/api/axiosInstance.ts

rewrites 설정 했습니다.
- rewrites에 url 추가
- axios 인스턴스에 baseURL 추가
api 통신을 할때는 아래 예시 코드와 같이 사용하면 됩니다.
```tsx
axiosInstance.get('/user');
```

[feat] rewrites 설정

---

src/components/EmptyProfile/EmptyProfile.css.ts
src/components/EmptyProfile/index.tsx
src/pageContainer/ProfilePages/ProfileListPage/index.tsx

> Empty Profile 컴포넌트 반응형 작업 완료했습니다.
https://github.com/user-attachments/assets/453d1ab4-8a34-4098-8d97-ce8b80a71621

[feat] Empty Profile 컴포넌트 반응형 작업

---

src/pageContainer/SignInPage/index.tsx
src/pageContainer/SignInPage/signIn.css.ts

로그인 페이지 반응형
로그인 페이지 반응형 작업 했습니다
https://github.com/user-attachments/assets/133b8eac-40d1-4011-995b-fd05757882ab

[Feat]로그인 페이지 반응형

---

src/pageContainer/SignUpPage/stepOne/index.tsx
src/pageContainer/SignUpPage/stepOne/signUpOne.css.ts
src/pageContainer/SignUpPage/stepTwo/index.tsx
src/pageContainer/SignUpPage/stepTwo/signUpTwo.css.ts

회원가입 페이지 반응형
회원가입 페이지 반응형 작업했습니다
step1
https://github.com/user-attachments/assets/63ac527b-1597-4cdd-97af-6252d39a22ae
step2
https://github.com/user-attachments/assets/cb0a58fe-fa57-4dae-90d1-5e9c3f064ad6

[Feat]회원가입 페이지 반응형

---

src/components/MainPage/Section1/index.tsx

메인 페이지 로그인 버튼 링크 범위 확대
- 기존 로그인 버튼은 내부 텍스트를 눌러야만 url이 이동이 되어서 범위를 버튼 전체로 확대했습니다.

[fix] 로그인 버튼 링크 범위 확대

---

src/components/ClubSelector/index.tsx
src/components/index.ts
src/pageContainer/ProfilePages/ProfileDetailPage/index.tsx
src/pageContainer/ProfilePages/ProfileListPage/index.tsx
src/pageContainer/ProfilePages/ProfileListPage/profileList.css.ts
src/types/index.ts
src/types/profileResponse.ts

> pull 과정 중 발생한 문제 해결을 위해 브랜치 재생성 및 코드 복구를 했습니다.
- `git pull`을 수행하는 도중, 예상치 못한 코드 누락 및 삭제가 발생했습니다. 이로 인해 일부 파일 및 코드가 누락된 상태에서 진행된 작업이 있었습니다.
- 브랜치를 새로 생성하고, 이전에 작업하던 브랜치의 코드 및 변경 사항을 복구하였습니다.
- PR 머지 후, 동일한 문제가 발생하지 않도록 코드 및 브랜치 관리 방법을 점검할 예정입니다.
- 코드 복구가 잘 이루어졌는지 확인 부탁드립니다.
- 추가적으로 필요한 수정사항이나 개선사항이 있는지 리뷰해 주세요.

[fix] pull 과정 중 발생한 문제 해결을 위해 브랜치 재생성 및 코드 복구

---

src/pageContainer/ProfilePages/ProfileDetailPage/index.tsx

> useAuth를 사용하여 로그인 상태를 가져옴 (getMyProfile에서 사용)

[fix] useAuth 사용 

---

src/components/Header/index.tsx

헤더 라우팅 수정
if문 뒤에 else문을 작성하지 않아 `/profile/'경로 이외에 모든 경로가 header를 통해 접근되지 않았던 오류 수정

[fix]header 라우팅 수정

---

src/pageContainer/ProfilePages/ProfileListPage/index.tsx
src/pageContainer/ProfilePages/ProfileListPage/profileList.css.ts

> 동아리 목록이 긴 경우 '···'으로 생략 처리하였습니다.
- 동아리 목록이 긴 경우 '···'으로 생략 처리
- profile list title 가운데 정렬
- profile list 최소 높이 설정

[feat] 동아리 목록이 긴 경우 '···'으로 생략 처리

---

src/libs/api/axiosInstance.ts
src/pageContainer/ClubsPage/index.tsx
src/pageContainer/ProfilePages/ProfileDetailPage/index.tsx
src/pageContainer/SignInPage/index.tsx
src/pageContainer/SignUpPage/stepTwo/index.tsx

불필요한 console제거
불필요한 `consoole.log`를 삭제했습니다
에러를 표시하는 `console.log`는 `console.error`로 교체했습니다
onError 헨들러는 사용을 하지 않을것 같아 삭제했습니다

[refactor]Console 제거

---

src/components/ClubCard/clubCard.css.ts
src/pageContainer/ClubsPage/index.tsx

동아리 카드 디자인 변경 및 사소한 리팩토링
- 동아리 카드 디자인에 맞게 수정
- axios 래핑 함수 사용하는 방식으로 변경
- useQuery 옵션 변경
- 에러 발생 시 토스트 띄우도록 변경

[feat] 동아리 카드 디자인 수정, axios 래퍼 적용 및 에러 핸들링 개선

---

src/libs/api/axiosInstance.ts

토큰 재발급 기능이 작동하지 않았던 오류 수정
1. 오류 상태 코드를 확인할때 `state`를 `status`로 수정했습니다
2. 토큰 재발급을 받은 후, 페이지를 새로고침 하여 최신 내용으로 반영되게 했습니다

[fix]토큰 재발급 로직 수정

---

next.config.ts
src/components/ClubCard/clubCard.css.ts
src/components/ClubCard/index.tsx
src/pageContainer/ClubsPage/clubs.css.ts
src/pageContainer/ClubsPage/index.tsx
src/types/clubResponse.ts

외부 이미지 도메인 설정과 각 동아리별 노션 링크 연결 완료했습니다
- next.config.ts 설정으로 외부 이미지 로딩 가능하도록 변경
- 각 동아리별 노션 링크 연결

[feat] 외부 이미지 도메인 설정 & 노션 링크 연결

---

src/app/password/page.tsx
src/pageContainer/PasswordPage/index.tsx
src/pageContainer/PasswordPage/password.css.ts
src/pageContainer/SignInPage/index.tsx
src/pageContainer/SignInPage/signIn.css.ts
src/pageContainer/index.ts

비밀번호 재설정 페이지를 제작했습니다
1. 로그인 페이지 하단 text에 `비밀번호 재설정` 엥커 추가
2. 비밀번호 재설정 페이지 제작

[feat]비밀번호 재설정 페이지
